/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
#include <stdlib.h>
#include "arp_request_lib.h"
/* Header for class com_github_JoeKerouac_nativenet_nativ_impl_NativeArpNetInterfaceImpl */

char* convert_jbytearray_to_chararray(JNIEnv *env, jbyteArray bytearray);

jbyteArray convert_chararray_to_jbytearray(JNIEnv *env, char *data, int data_len);

/*
 * Class:     com_github_JoeKerouac_nativenet_nativ_impl_NativeArpNetInterfaceImpl
 * Method:    _createSock
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_JoeKerouac_nativenet_nativ_impl_NativeArpNetInterfaceImpl__1createSock
  (JNIEnv *env, jobject nativeArpNetInterfaceImpl){
    return create_arp_socket();
}

/*
 * Class:     com_github_JoeKerouac_nativenet_nativ_impl_NativeArpNetInterfaceImpl
 * Method:    _close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_github_JoeKerouac_nativenet_nativ_impl_NativeArpNetInterfaceImpl__1close
  (JNIEnv *env, jobject nativeArpNetInterfaceImpl, jint sock){
    close_arp_socket(sock);
}

/*
 * Class:     com_github_JoeKerouac_nativenet_nativ_impl_NativeArpNetInterfaceImpl
 * Method:    _sendArp
 * Signature: (Lcom/github/JoeKerouac/nativenet/nativ/ArpData;I)I
 */
JNIEXPORT jint JNICALL Java_com_github_JoeKerouac_nativenet_nativ_impl_NativeArpNetInterfaceImpl__1sendArp
  (JNIEnv *env, jobject nativeArpNetInterfaceImpl, jobject arpData, jint sock){
  jclass arpDataClass = (*env)->GetObjectClass(env, arpData);

  jfieldID srcIpId = (*env)->GetFieldID(env, arpDataClass, "srcIp", "[B");
  jobject srcIpObj = (*env)->GetObjectField(env, arpData, srcIpId);
  jbyteArray srcIpByteArray = (jbyteArray) srcIpObj;
  char *srcIp = convert_jbytearray_to_chararray(env, srcIpByteArray);

  jfieldID srcMacId = (*env)->GetFieldID(env, arpDataClass, "srcMac", "[B");
  jobject srcMacObj = (*env)->GetObjectField(env, arpData, srcMacId);
  jbyteArray srcMacByteArray = (jbyteArray) srcMacObj;
  char *srcMac = convert_jbytearray_to_chararray(env, srcMacByteArray);

  jfieldID destIpId = (*env)->GetFieldID(env, arpDataClass, "destIp", "[B");
  jobject destIpObj = (*env)->GetObjectField(env, arpData, destIpId);
  jbyteArray destIpByteArray = (jbyteArray) destIpObj;
  char *destIp = convert_jbytearray_to_chararray(env, destIpByteArray);


  jfieldID destMacId = (*env)->GetFieldID(env, arpDataClass, "destMac", "[B");
  jobject destMacObj = (*env)->GetObjectField(env, arpData, destMacId);
  jbyteArray destMacByteArray = (jbyteArray) destMacObj;
  char *destMac = convert_jbytearray_to_chararray(env, destMacByteArray);

  return send_arp(sock, srcMac, srcIp, destMac, destIp);
}

/*
 * Class:     com_github_JoeKerouac_nativenet_nativ_impl_NativeArpNetInterfaceImpl
 * Method:    _receive_arp
 * Signature: (I)Lcom/github/JoeKerouac/nativenet/nativ/ArpData;
 */
JNIEXPORT jobject JNICALL Java_com_github_JoeKerouac_nativenet_nativ_impl_NativeArpNetInterfaceImpl__1receive_1arp
  (JNIEnv *env, jobject nativeArpNetInterfaceImpl, jint sock){
  struct arppacket *msg;
  void *realData = malloc(arl_get_arppacket_size());
  int result = receive_arp(sock, realData);

  if (receive_arp(sock, realData) <= 0){
    // 调用失败
    return NULL;
  }

  msg = (struct arppacket *)realData;

  jclass arpDataClass = (*env)->FindClass(env, "com/github/JoeKerouac/nativenet/nativ/ArpData");
  jmethodID constructorMethod = (*env)->GetMethodID(env, arpDataClass, "<init>", "()V");
  jobject arpData = (*env)->NewObject(env, arpDataClass, constructorMethod);



  jfieldID srcIpId = (*env)->GetFieldID(env, arpDataClass, "srcIp", "[B");
  char *srcIpData;
  srcIpData = arl_get_src_ip(msg);
  jbyteArray srcIp = convert_chararray_to_jbytearray(env, srcIpData, 4);
  (*env)->SetObjectField(env, arpData, srcIpId, srcIp);

  jfieldID srcMacId = (*env)->GetFieldID(env, arpDataClass, "srcMac", "[B");
  char *srcMacData;
  srcMacData = arl_get_src_mac(msg);
  jbyteArray srcMac = convert_chararray_to_jbytearray(env, srcMacData, 6);
  (*env)->SetObjectField(env, arpData, srcMacId, srcMac);

  jfieldID destIpId = (*env)->GetFieldID(env, arpDataClass, "destIp", "[B");
  char *destIpData;
  destIpData = arl_get_dest_ip(msg);
  jbyteArray destIp = convert_chararray_to_jbytearray(env, destIpData, 4);
  (*env)->SetObjectField(env, arpData, destIpId, destIp);


  jfieldID destMacId = (*env)->GetFieldID(env, arpDataClass, "destMac", "[B");
  char *destMacData;
  destMacData = arl_get_dest_mac(msg);
  jbyteArray destMac = convert_chararray_to_jbytearray(env, destMacData, 6);
  (*env)->SetObjectField(env, arpData, destMacId, destMac);

  free(realData);

  return arpData;
}

jbyteArray convert_chararray_to_jbytearray(JNIEnv *env, char *data, int data_len) {
    jbyteArray result = (*env)->NewByteArray(env, data_len);
    (*env)->SetByteArrayRegion(env, result, 0, data_len, data);
    return result;
}

char* convert_jbytearray_to_chararray(JNIEnv *env, jbyteArray bytearray) {
    jbyte *bytes;
    int chars_len = (*env)->GetArrayLength(env, bytearray);
    (*env)->GetByteArrayRegion(env, bytearray, 0, chars_len, bytes);
    return bytes;
}

//char* convert_jbytearray_to_chararray(JNIEnv *env, jbyteArray bytearray) {
//    char *chars = NULL;
//    jbyte *bytes;
//    bytes = (*env)->GetByteArrayElements(env, bytearray, 0);
//    int chars_len = (*env)->GetArrayLength(env, bytearray);
//    chars = malloc(chars_len);
//    memset(chars, 0, chars_len);
//    memcpy(chars, bytes, chars_len);
//
//    (*env)->ReleaseByteArrayElements(env, bytearray, bytes, 0);
//
//    return chars;
//}