/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_JoeKerouac_nativenet_nativ_impl_NativeArpNetInterfaceImpl */

#ifndef _Included_com_github_JoeKerouac_nativenet_nativ_impl_NativeArpNetInterfaceImpl
#define _Included_com_github_JoeKerouac_nativenet_nativ_impl_NativeArpNetInterfaceImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_JoeKerouac_nativenet_nativ_impl_NativeArpNetInterfaceImpl
 * Method:    _createSock
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_JoeKerouac_nativenet_nativ_impl_NativeArpNetInterfaceImpl__1createSock
  (JNIEnv *, jobject);

/*
 * Class:     com_github_JoeKerouac_nativenet_nativ_impl_NativeArpNetInterfaceImpl
 * Method:    _close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_github_JoeKerouac_nativenet_nativ_impl_NativeArpNetInterfaceImpl__1close
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_github_JoeKerouac_nativenet_nativ_impl_NativeArpNetInterfaceImpl
 * Method:    _sendArp
 * Signature: (Lcom/github/JoeKerouac/nativenet/nativ/ArpData;I)I
 */
JNIEXPORT jint JNICALL Java_com_github_JoeKerouac_nativenet_nativ_impl_NativeArpNetInterfaceImpl__1sendArp
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_github_JoeKerouac_nativenet_nativ_impl_NativeArpNetInterfaceImpl
 * Method:    _receive_arp
 * Signature: (I)Lcom/github/JoeKerouac/nativenet/nativ/ArpData;
 */
JNIEXPORT jobject JNICALL Java_com_github_JoeKerouac_nativenet_nativ_impl_NativeArpNetInterfaceImpl__1receive_1arp
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
