/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
#include <stdlib.h>
#include "nf_userspace_queue.h"
/* Header for class com_github_JoeKerouac_nativenet_nativ_impl_NativeNetFilterInterfaceImpl */

#ifndef _Included_com_github_JoeKerouac_nativenet_nativ_impl_NativeNetFilterInterfaceImpl
#define _Included_com_github_JoeKerouac_nativenet_nativ_impl_NativeNetFilterInterfaceImpl
#ifdef __cplusplus
extern "C" {
#endif

jobject *_callback;
JavaVM *g_jvm;


struct callback_data * data_convert_to_c(JNIEnv *env, jobject netFilterCallbackData);

jobject data_convert_to_java(JNIEnv *env, struct callback_data *data);

void set_java_obj_field(JNIEnv *env, jobject dest, char *field_name, char *sig, jobject jobj);

void set_java_short_field(JNIEnv *env, jobject dest, char *field_name, char *sig, jshort jobj);

void set_java_int_field(JNIEnv *env, jobject dest, char *field_name, char *sig, jint jobj);

short get_java_short_field(JNIEnv *env, jobject dest, char *field_name);

int get_java_int_field(JNIEnv *env, jobject dest, char *field_name);

char* get_java_bytearray_field(JNIEnv *env, jobject dest, char *field_name);

jobject new_java_instance(JNIEnv *env, char *class_name);

jbyteArray convert_chararray_to_jbytearray(JNIEnv *env, char *data, int data_len) ;

char* convert_jbytearray_to_chararray(JNIEnv *env, jbyteArray bytearray) ;

void nf_callback(struct callback_data *data);


/**
 * @brief nf_userspace_queue的回调函数
 * @param data 回调数据
 * @param netFilterCallbackData NetFilterCallbackData对象
 */
void nf_callback(struct callback_data *data) {
    JNIEnv env;
    // 获取JNIEnv
    g_jvm->AttachCurrentThread(g_jvm, &env, NULL);
    jclass clazz = env->GetObjectClass(&env, *_callback);
    jmethodID methodId = env->GetMethodID(&env, clazz, "accept", "(Lcom/github/JoeKerouac/nativenet/nativ/NetFilterCallbackData;)V");
    jobject jobj = data_convert_to_java(&env, data);
    env->CallVoidMethod(&env, *_callback, methodId, jobj);
}

/**
 * @brief 将NetFilterCallbackData转换为callback_data结构体
 * @param env JNI环境
 * @param netFilterCallbackData NetFilterCallbackData对象
 * @return callback_data结构体指针，使用完毕需要自己free
 */
struct callback_data * data_convert_to_c(JNIEnv *env, jobject netFilterCallbackData){
    struct callback_data *callback_data;
    callback_data = malloc_callback_data();

    char *data;
    data = get_java_bytearray_field(env, netFilterCallbackData, "data");

    nfuq_set_data(callback_data, data);
    nfuq_set_data_len(callback_data, get_java_short_field(env, netFilterCallbackData, "dataLen"));
    nfuq_set_queue_num(callback_data, get_java_int_field(env, netFilterCallbackData, "queueNum"));
    nfuq_set_hook_num(callback_data, get_java_int_field(env, netFilterCallbackData, "hookNum"));
    nfuq_set_id(callback_data, get_java_int_field(env, netFilterCallbackData, "id"));
    return callback_data;
}


/**
 * @brief 将callback_data结构体转换为NetFilterCallbackData对象
 * @param env JNI环境
 * @param data callback_data结构体
 * @return NetFilterCallbackData对象
 */
jobject data_convert_to_java(JNIEnv *env, struct callback_data *data){
    jobject netFilterCallbackData = new_java_instance(env, "com/github/JoeKerouac/nativenet/nativ/NetFilterCallbackData");
    jbyteArray array =  convert_chararray_to_jbytearray(env, nfuq_read_data(data), nfuq_read_data_len(data));
    set_java_obj_field(env, netFilterCallbackData, "data", "[B", array);
    set_java_short_field(env, netFilterCallbackData, "dataLen", "S", nfuq_read_data_len(data));
    set_java_int_field(env, netFilterCallbackData, "queueNum", "I", nfuq_read_queue_num(data));
    set_java_int_field(env, netFilterCallbackData, "hookNum", "I", nfuq_read_hook_num(data));
    set_java_int_field(env, netFilterCallbackData, "id", "I", nfuq_read_id(data));

    return netFilterCallbackData;
}

/**
 * @brief 设置指定对象的指定字段
 * @param env JNI环境
 * @param dest 指定对象
 * @param field_name 指定字段名
 * @param sig 指定字段签名
 * @param jobj 要设置的值
 */
void set_java_obj_field(JNIEnv *env, jobject dest, char *field_name, char *sig, jobject jobj){
    jclass clazz = (*env)->GetObjectClass(env, dest);
    jfieldID field_id = (*env)->GetFieldID(env, clazz, field_name, sig);
    (*env)->SetObjectField(env, dest, field_id, jobj);
}

/**
 * @brief 设置指定对象的指定字段
 * @param env JNI环境
 * @param dest 指定对象
 * @param field_name 指定字段名
 * @param sig 指定字段签名
 * @param jobj 要设置的值
 */
void set_java_short_field(JNIEnv *env, jobject dest, char *field_name, char *sig, jshort jobj){
    jclass clazz = (*env)->GetObjectClass(env, dest);
    jfieldID field_id = (*env)->GetFieldID(env, clazz, field_name, sig);
    (*env)->SetShortField(env, dest, field_id, jobj);
}

/**
 * @brief 设置指定对象的指定字段
 * @param env JNI环境
 * @param dest 指定对象
 * @param field_name 指定字段名
 * @param sig 指定字段签名
 * @param jobj 要设置的值
 */
void set_java_int_field(JNIEnv *env, jobject dest, char *field_name, char *sig, jint jobj){
    jclass clazz = (*env)->GetObjectClass(env, dest);
    jfieldID field_id = (*env)->GetFieldID(env, clazz, field_name, sig);
    (*env)->SetIntField(env, dest, field_id, jobj);
}

short get_java_short_field(JNIEnv *env, jobject dest, char *field_name){
    jclass clazz = (*env)->GetObjectClass(env, dest);
    jfieldID field_id = (*env)->GetFieldID(env, clazz, field_name, "S");
    return (*env)->GetShortField(env, dest, field_id);
}

int get_java_int_field(JNIEnv *env, jobject dest, char *field_name){
    jclass clazz = (*env)->GetObjectClass(env, dest);
    jfieldID field_id = (*env)->GetFieldID(env, clazz, field_name, "I");
    return (*env)->GetIntField(env, dest, field_id);
}

char* get_java_bytearray_field(JNIEnv *env, jobject dest, char *field_name){
    jclass clazz = (*env)->GetObjectClass(env, dest);
    jfieldID field_id = (*env)->GetFieldID(env, clazz, field_name, "[B");
    jobject bytearray = (*env)->GetObjectField(env, dest, field_id);
    return convert_jbytearray_to_chararray(env, bytearray);
}

/**
 * @brief 调用指定类型的无参构造器构造对象实例
 * @param env JNI环境
 * @param class_name class全称，例如com/github/JoeKerouac/nativenet/nativ/ArpData
 * @return 对象实例
 */
jobject new_java_instance(JNIEnv *env, char *class_name){
  jclass clazz = (*env)->FindClass(env, class_name);
  jmethodID constructorMethod = (*env)->GetMethodID(env, clazz, "<init>", "()V");
  jobject instance = (*env)->NewObject(env, clazz, constructorMethod);
  return instance;
}

/**
 * @brief 将char*转换为Java原生byte数组
 * @param env JNI环境
 * @param data char数组
 * @param data_len 数组长度
 * @return Java原生byte数组
 */
jbyteArray convert_chararray_to_jbytearray(JNIEnv *env, char *data, int data_len) {
    jbyteArray result = (*env)->NewByteArray(env, data_len);
    (*env)->SetByteArrayRegion(env, result, 0, data_len, data);
    return result;
}

/**
 * @brief 将Java原生byte数组转换为char数组
 * @param env JNI环境
 * @param bytearray Java原生byte数组
 * @return char数组
 */
char* convert_jbytearray_to_chararray(JNIEnv *env, jbyteArray bytearray) {
    char *chars = NULL;
    jbyte *bytes;
    bytes = (*env)->GetByteArrayElements(env, bytearray, 0);
    int chars_len = (*env)->GetArrayLength(env, bytearray);
    chars = malloc(chars_len);
    memset(chars, 0, chars_len);
    memcpy(chars, bytes, chars_len);

    (*env)->ReleaseByteArrayElements(env, bytearray, bytes, 0);

    return chars;
}


/*
 * Class:     com_github_JoeKerouac_nativenet_nativ_impl_NativeNetFilterInterfaceImpl
 * Method:    _run
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_github_JoeKerouac_nativenet_nativ_impl_NativeNetFilterInterfaceImpl__1run
  (JNIEnv *env, jobject nativeNetFilterInterfaceImpl, jint queueNum){
    nfuq_register(&nf_callback);
    nfuq_run(queueNum);
    // JNIEnv只能当前线程使用，不能多线程用，所以这里保存JavaVM供后续使用
    (*env)->GetJavaVM(env, &g_jvm);
}

/*
 * Class:     com_github_JoeKerouac_nativenet_nativ_impl_NativeNetFilterInterfaceImpl
 * Method:    _register
 * Signature: (Ljava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_com_github_JoeKerouac_nativenet_nativ_impl_NativeNetFilterInterfaceImpl__1register
  (JNIEnv *env, jobject nativeNetFilterInterfaceImpl, jobject callback) {
    _callback = &callback;
}

/*
 * Class:     com_github_JoeKerouac_nativenet_nativ_impl_NativeNetFilterInterfaceImpl
 * Method:    _sendVerdict
 * Signature: (Lcom/github/JoeKerouac/nativenet/nativ/NetFilterCallbackData;I)V
 */
JNIEXPORT void JNICALL Java_com_github_JoeKerouac_nativenet_nativ_impl_NativeNetFilterInterfaceImpl__1sendVerdict
  (JNIEnv *env, jobject nativeNetFilterInterfaceImpl, jobject netFilterCallbackData, jint verdict){
    struct callback_data *data = data_convert_to_c(env, netFilterCallbackData);
    nfuq_send_verdict(nfuq_read_queue_num(data), nfuq_read_id(data), nfuq_read_data_len(data),
      nfuq_read_data(data), verdict);
}


#ifdef __cplusplus
}
#endif
#endif
