/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_JoeKerouac_nativenet_nativ_impl_NativeNetFilterInterfaceImpl */

#ifndef _Included_com_github_JoeKerouac_nativenet_nativ_impl_NativeNetFilterInterfaceImpl
#define _Included_com_github_JoeKerouac_nativenet_nativ_impl_NativeNetFilterInterfaceImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_JoeKerouac_nativenet_nativ_impl_NativeNetFilterInterfaceImpl
 * Method:    _run
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_github_JoeKerouac_nativenet_nativ_impl_NativeNetFilterInterfaceImpl__1run
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_github_JoeKerouac_nativenet_nativ_impl_NativeNetFilterInterfaceImpl
 * Method:    _register
 * Signature: (Ljava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_com_github_JoeKerouac_nativenet_nativ_impl_NativeNetFilterInterfaceImpl__1register
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_github_JoeKerouac_nativenet_nativ_impl_NativeNetFilterInterfaceImpl
 * Method:    _sendVerdict
 * Signature: (Lcom/github/JoeKerouac/nativenet/nativ/NetFilterCallbackData;I)V
 */
JNIEXPORT void JNICALL Java_com_github_JoeKerouac_nativenet_nativ_impl_NativeNetFilterInterfaceImpl__1sendVerdict
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
