# 注意，本地库编译依赖的arp_request_lib.o和nf_userspace_queue.o这两个私有库需要自己编译，源码在clib库中
# 编译上述两个库的时候需要使用gcc -fPIC -shared 命令来编译，同时-l选项也是必不可少的，不然链接库会找不到（不加的话只会从当前目录查找）


# 编译arp本地库
gcc -fPIC -shared com_github_JoeKerouac_nativenet_nativ_impl_NativeArpNetInterfaceImpl.c -larp_request_lib -o libcom_github_JoeKerouac_nativenet_nativ_impl_NativeArpNetInterfaceImpl.so
# 编译netfilter本地库
gcc -fPIC -shared com_github_JoeKerouac_nativenet_nativ_impl_NativeNetFilterInterfaceImpl.c -lnf_userspace_queue -o libcom_github_JoeKerouac_nativenet_nativ_impl_NativeNetFilterInterfaceImpl.so